# Cors Config
FRONT_END_URL=http://locahost:3000

# JWT Constant
JWT_HEADER=DummyHeader
JWT_KEY=dummysecretkeyM3t4Qjdsfafasdfdsaf32984723=24c3QyZlV3c22112Zmcndac2RkZGYxZXJkZ231jhjkfdsa==93jk-3=320o3jlk

# Access Token Properties
TTL_ACCESS_TOKEN=30

# Cors Config
# FRONT_END_URL=https://www.eccubestudio.click
BACK_END_URL=http://localhost:8080

# Verify Token Properties
TOKEN_EMAIL=60
TOKEN_RESET_PASSWORD=60

# Mail A&A
EMAIL_FROM=dummyemail@gmail.com
SENDGRID_API_KEY=dummySecretKey
VERIFY_API=/dummy-url?token=

# Google
GOOGLE_REDIRECT_URI=dummy-redirect-url
GOOGLE_CLIENT_SECRET=dummy-client-secrect
GOOGLE_CLIENT_ID=dummy-client-id

# Admin Account
ADMIN_EMAIL=dummy-email

# Cloudinary
CLOUD_NAME=dummy-name
CLOUD_API_KEY=dummy-api-key
CLOUD_API_SECRET=dummy-api-secret