name: Continuous Integration

# Kích hoạt workflow này khi có sự kiện push lên nhánh main (bao gồm merge)
on:
  push:
    branches:
      - main  # Branch name for deployment


jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Sử dụng hệ điều hành Ubuntu mới nhất để chạy workflow

    steps:
      # Tải mã nguồn từ GitHub xuống môi trường chạy
      - name: Checkout code
        uses: actions/checkout@v2 # Tải mã nguồn từ GitHub xuống

      - name: Build Docker Image
        run: docker build -t booking-studio . # Dựa vào Dockerfile để build image

      # Cài đặt wait-for-it và curl
      - name: Install dependencies for health check
        run: |
          sudo apt-get update
          sudo apt-get install -y wait-for-it curl

      - name: Run Docker Container and Check Health
        # http://localhost:8080/health dùng để kiểm tra ứng dụng bên trong máy chủ ảo của GitHub Actions
        # wait-for-it sẽ đợi tối đa 60s cho cổng 8080 mở
        # Kích hoạt profile 'ci' để ứng dụng dùng H2 DB thay vì DB thật
        run: |
          docker run -d -p 8080:8080 --name studio-app \
            -e SPRING_PROFILES_ACTIVE=ci \
            booking-studio
          wait-for-it localhost:8080 -t 60 --strict
          echo "Port is open. Waiting 10 seconds for Spring Boot to stabilize..."
          sleep 10
          curl -f http://localhost:8080/health || (echo "Health check failed" && exit 1)

      - name: Run unit tests
        run: |
          ./gradlew test
